package input;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.HashMap;

public class Utils {
	public static HashMap<String, Integer[]> keyCodes = new HashMap<>();
	public static void init() {
		keyCodes.put("a", new Integer[] {KeyEvent.VK_A});
		keyCodes.put("b", new Integer[] {KeyEvent.VK_B});
		keyCodes.put("c", new Integer[] {KeyEvent.VK_C});
		keyCodes.put("d", new Integer[] {KeyEvent.VK_D});
		keyCodes.put("e", new Integer[] {KeyEvent.VK_E});
		keyCodes.put("f", new Integer[] {KeyEvent.VK_F});
		keyCodes.put("g", new Integer[] {KeyEvent.VK_G});
		keyCodes.put("h", new Integer[] {KeyEvent.VK_H});
		keyCodes.put("i", new Integer[] {KeyEvent.VK_I});
		keyCodes.put("j", new Integer[] {KeyEvent.VK_J});
		keyCodes.put("k", new Integer[] {KeyEvent.VK_K});
		keyCodes.put("l", new Integer[] {KeyEvent.VK_L});
		keyCodes.put("m", new Integer[] {KeyEvent.VK_M});
		keyCodes.put("n", new Integer[] {KeyEvent.VK_N});
		keyCodes.put("o", new Integer[] {KeyEvent.VK_O});
		keyCodes.put("p", new Integer[] {KeyEvent.VK_P});
		keyCodes.put("q", new Integer[] {KeyEvent.VK_Q});
		keyCodes.put("r", new Integer[] {KeyEvent.VK_R});
		keyCodes.put("s", new Integer[] {KeyEvent.VK_S});
		keyCodes.put("t", new Integer[] {KeyEvent.VK_T});
		keyCodes.put("u", new Integer[] {KeyEvent.VK_U});
		keyCodes.put("v", new Integer[] {KeyEvent.VK_V});
		keyCodes.put("w", new Integer[] {KeyEvent.VK_W});
		keyCodes.put("x", new Integer[] {KeyEvent.VK_X});
		keyCodes.put("y", new Integer[] {KeyEvent.VK_Y});
		keyCodes.put("z", new Integer[] {KeyEvent.VK_Z});
		keyCodes.put("1", new Integer[] {KeyEvent.VK_1});
		keyCodes.put("2", new Integer[] {KeyEvent.VK_2});
		keyCodes.put("3", new Integer[] {KeyEvent.VK_3});
		keyCodes.put("4", new Integer[] {KeyEvent.VK_4});
		keyCodes.put("5", new Integer[] {KeyEvent.VK_5});
		keyCodes.put("6", new Integer[] {KeyEvent.VK_6});
		keyCodes.put("7", new Integer[] {KeyEvent.VK_7});
		keyCodes.put("8", new Integer[] {KeyEvent.VK_8});
		keyCodes.put("9", new Integer[] {KeyEvent.VK_9});
		keyCodes.put("0", new Integer[] {KeyEvent.VK_0});
		keyCodes.put("_", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_MINUS});
		keyCodes.put("=", new Integer[] {KeyEvent.VK_EQUALS});
		keyCodes.put("+", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_EQUALS});
		keyCodes.put("-", new Integer[] {KeyEvent.VK_MINUS});
		keyCodes.put("(", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_9});
		keyCodes.put(")", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_0});
		keyCodes.put("*", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_8});
		keyCodes.put("&", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_7});
		keyCodes.put("^", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_6});
		keyCodes.put("%", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_5});
		keyCodes.put("$", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_4});
		keyCodes.put("#", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_3});
		keyCodes.put("@", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_2});
		keyCodes.put("<", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_COMMA});
		keyCodes.put(">", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_PERIOD});
		keyCodes.put("/", new Integer[] {KeyEvent.VK_SLASH});
		keyCodes.put(":", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_SEMICOLON});
		keyCodes.put(";", new Integer[] {KeyEvent.VK_SEMICOLON});
		keyCodes.put("[", new Integer[] {KeyEvent.VK_OPEN_BRACKET});
		keyCodes.put("]", new Integer[] {KeyEvent.VK_CLOSE_BRACKET});
		keyCodes.put("{", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_OPEN_BRACKET});
		keyCodes.put("}", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_CLOSE_BRACKET});
		keyCodes.put("\\", new Integer[] {KeyEvent.VK_BACK_SLASH});
		keyCodes.put("|", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_BACK_SLASH});
		keyCodes.put("\'", new Integer[] {KeyEvent.VK_QUOTE});
		keyCodes.put("\"", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_QUOTE});
		keyCodes.put("!", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_1});
		keyCodes.put("?", new Integer[] {KeyEvent.VK_SHIFT, KeyEvent.VK_SLASH});
		keyCodes.put(",", new Integer[] {KeyEvent.VK_COMMA});
		keyCodes.put(".", new Integer[] {KeyEvent.VK_PERIOD});
		keyCodes.put("altTab", new Integer[] {KeyEvent.VK_ALT, KeyEvent.VK_TAB});
		keyCodes.put("space", new Integer[] {KeyEvent.VK_SPACE});
		keyCodes.put("tab", new Integer[] {KeyEvent.VK_TAB});
		keyCodes.put("backspace", new Integer[] {KeyEvent.VK_BACK_SPACE});
		keyCodes.put("enter", new Integer[] {KeyEvent.VK_ENTER});
		keyCodes.put("leftArrow", new Integer[] {KeyEvent.VK_LEFT});
		keyCodes.put("rightArrow", new Integer[] {KeyEvent.VK_RIGHT});
		keyCodes.put("upArrow", new Integer[] {KeyEvent.VK_UP});
		keyCodes.put("downArrow", new Integer[] {KeyEvent.VK_DOWN});
		keyCodes.put("ctrl", new Integer[] {KeyEvent.VK_CONTROL});
		keyCodes.put("alt", new Integer[] {KeyEvent.VK_ALT});
		keyCodes.put("shift", new Integer[] {KeyEvent.VK_SHIFT});
		keyCodes.put("windows", new Integer[] {KeyEvent.VK_WINDOWS});
		keyCodes.put("escape", new Integer[] {KeyEvent.VK_ESCAPE});
		keyCodes.put("numLock", new Integer[] {KeyEvent.VK_NUM_LOCK});
		keyCodes.put("capsLock", new Integer[] {KeyEvent.VK_CAPS_LOCK});
		keyCodes.put("delete", new Integer[] {KeyEvent.VK_DELETE});
		keyCodes.put("f1", new Integer[] {KeyEvent.VK_F1});
		keyCodes.put("f2", new Integer[] {KeyEvent.VK_F2});
		keyCodes.put("f3", new Integer[] {KeyEvent.VK_F3});
		keyCodes.put("f4", new Integer[] {KeyEvent.VK_F4});
		keyCodes.put("f5", new Integer[] {KeyEvent.VK_F5});
		keyCodes.put("f6", new Integer[] {KeyEvent.VK_F6});
		keyCodes.put("f7", new Integer[] {KeyEvent.VK_F7});
		keyCodes.put("f8", new Integer[] {KeyEvent.VK_F8});
		keyCodes.put("f9", new Integer[] {KeyEvent.VK_F9});
		keyCodes.put("f10", new Integer[] {KeyEvent.VK_F10});
		keyCodes.put("f11", new Integer[] {KeyEvent.VK_F11});
		keyCodes.put("f12", new Integer[] {KeyEvent.VK_F12});
		keyCodes.put("home", new Integer[] {KeyEvent.VK_HOME});
		keyCodes.put("end", new Integer[] {KeyEvent.VK_END});
		keyCodes.put("pageUp", new Integer[] {KeyEvent.VK_PAGE_UP});
		keyCodes.put("pageDown", new Integer[] {KeyEvent.VK_PAGE_DOWN});
		keyCodes.put("leftClick", new Integer[] {MouseEvent.BUTTON1_MASK});
		keyCodes.put("middleClick", new Integer[] {MouseEvent.BUTTON2_MASK});
		keyCodes.put("rightClick", new Integer[] {MouseEvent.BUTTON3_MASK});
	}

	public static boolean isWithin(double a, double b, double threshold) {
		return b <= a + threshold && b >= a - threshold;
	}
}
